#!/bin/bash
mode=`lsusb | grep 0403 | sed 's/.*\(ID\) \([0-9a-f]*\):\([0-9a-f]*\).*/\3/'`
if [ $mode == "8398" ]
  then
    echo "Already in the correct mode"
    exit
fi
rmmod ftdi_sio
./set_fifo_mode
sleep 1s
devFolder=`lsusb | grep 0403 | sed 's/Bus \([0-9]*\) Device \([0-9]*\).*/\1\/\2/'`
./usbreset `echo "/dev/bus/usb/$devFolder"`
